[package]
name = "raspi-car"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rust_gpiozero = "0.2.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
